//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID_Pro { get; set; }
        public string Name_pro { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> qty { get; set; }
        public string location { get; set; }
        public byte[] img { get; set; }
        public Nullable<int> idItem { get; set; }
        public Nullable<int> idivo { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual item item { get; set; }
    }
}
